In [9]:
from transformers import AutoTokenizer, AutoModel
import torch
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer
# from nltk import SentenceTokenizer

# model_name = "bert-base-uncased"
# tokenizer = AutoTokenizer.from_pretrained(model_name)
# model = AutoModel.from_pretrained(model_name)

model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')
# embeddings = model.encode(sentences)
# print(embeddings)

def get_sentence_embedding(text):
    # inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True, max_length=512)
    # with torch.no_grad():
    #     outputs = model(**inputs)
    # return outputs.last_hidden_state[:, 0, :].numpy()
    return model.encode(text)

def cos_sim(a,b):
    return (np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))).sum()

def find_best_fit(slides, sentence):
    para_sentences = slides
    
    sentence_embedding_repeated = [get_sentence_embedding(sentence)] * len(para_sentences)
    para_embeddings = [get_sentence_embedding(sent) for sent in para_sentences]

    # print(sentence_embedding.shape)
    print([p.shape for p in para_embeddings])
    similarities = [cosine_similarity(a.reshape(1,-1),b.reshape(1,-1)) for a,b in zip(para_embeddings,sentence_embedding_repeated)]
    
    return similarities

In [16]:
speech = """lightning"""

In [14]:
import os
directory = './slides'
file_scores = {}
files = []
i=0

for filename in os.listdir(directory):
    # Create the full path to the file
    file_path = os.path.join(directory, filename)
    
    # Check if it's a file (not a directory)
    if os.path.isfile(file_path):
        print(f"Processing slide: {filename}")
        file_scores[i] = filename
        files.append(open(file_path,'r').read())
    i+=1

Processing slide: apollo.txt
Processing slide: athena.txt
Processing slide: hera.txt
Processing slide: poseidon.txt
Processing slide: zeus.txt


In [17]:
find_best_fit(files, speech)
# print(f"Input sentence: '{speech}'")
# print('--------------')
# print(f"Best fit at index {index}: '{best_match}' with similarity score {score:.4f}")

[(384,), (384,), (384,), (384,), (384,)]


[array([[0.07548838]], dtype=float32),
 array([[0.03851165]], dtype=float32),
 array([[-0.00032955]], dtype=float32),
 array([[0.31089544]], dtype=float32),
 array([[0.12468115]], dtype=float32)]

In [39]:
file_scores[2]

'hera.txt'